Repository MogakGround/Mogak-Client, pull requests merged in 2025-02, with the labels that each got.

#4 💄Design: 글로벌 컴포넌트 제작
  package-lock.json
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/svg/down-arrow-gray.svg
  src/assets/svg/down-arrow-white.svg
  src/assets/svg/logo.svg
  src/assets/svg/moon-accent-l.svg
  src/assets/svg/moon-accent-m.svg
  src/assets/svg/moon-accent-s.svg
  src/assets/svg/moon-gray-l.svg
  src/assets/svg/moon-gray-m.svg
  src/assets/svg/moon-gray-s.svg
  src/assets/svg/moon-primary-l.svg
  src/assets/svg/moon-primary-m.svg
  src/assets/svg/moon-primary-s.svg
  src/assets/svg/up-arrow-white.svg
  src/assets/svg/x-primary-dark.svg
  src/assets/svg/x-primary-light.svg
  src/components/Global/Dropdown/DefaultDropdown.tsx
  src/components/Global/chip/MoonChip.tsx
  src/components/Global/chip/MoonTextChip.tsx
  src/components/Global/chip/TextChip.tsx
  src/components/Global/chip/chip.style.tsx
  src/components/Global/chip/chip.types.ts
  src/components/Global/toast/IconToast.tsx
  src/components/Global/toast/TextToast.tsx
  src/components/Global/toast/toast.style.tsx
  src/components/Global/toast/toast.types.ts
  src/components/Global/toggle/TextToggle.tsx
  src/components/Global/toggle/toggle.style.tsx
  src/components/Global/toggle/toggle.types.ts
  src/components/Layout/Footer.tsx
  src/components/Layout/GNB.tsx
  src/components/Layout/Header.tsx
Labels: 💄 Design

#20 Chore/#19 cn함수도입 tailwindcss설정
  package-lock.json
  package.json
  src/components/global/input/IconInput.tsx
  src/utils/cn.ts
  tailwind.config.ts
Labels: ⚙️ Chore

#14 💄 Design: 공통 modal 컴포넌트 생성
  src/app/layout.tsx
  src/components/global/modal/Modal.tsx
  src/components/global/modal/Portal.tsx
  src/components/global/modal/hooks/useModal.tsx
Labels: 💄 Design

#15 💄 Design: 페이지네이션 컴포넌트 제작
  src/assets/svg/arrow-firstpage-disabled.svg
  src/assets/svg/arrow-firstpage.svg
  src/assets/svg/arrow-lastpage-disabled.svg
  src/assets/svg/arrow-lastpage.svg
  src/assets/svg/arrow-nextpage-disabled.svg
  src/assets/svg/arrow-nextpage.svg
  src/assets/svg/arrow-prevpage-disabled.svg
  src/assets/svg/arrow-prevpage.svg
  src/components/global/pagenation/Pagenation.tsx
  src/components/global/pagenation/pagenation.style.tsx
Labels: 💄 Design

#18 💄 Design: 토스트 컴포넌트 디자인 수정
  src/components/global/toast/AutoDisappearIconToast.tsx
  src/components/global/toast/AutoDisappearTextToast.tsx
  src/components/global/toast/IconToast.tsx
  src/components/global/toast/TextToast.tsx
  src/components/global/toast/toast.style.tsx
  src/components/global/toast/toast.types.ts
Labels: 💄 Design

#21 💄 Design: 회원가입/로그인 페이지 퍼블리싱
  public/images/bg-image.jpg
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/assets/svg/illust_block.svg
  src/assets/svg/illust_search.svg
  src/assets/svg/kakao-logo.svg
  src/components/auth/AuthLayout.tsx
  src/components/auth/NicknameInput.tsx
  src/components/auth/PortfolioInput.tsx
  src/components/auth/SignUpButtonGroup.tsx
  src/components/auth/SignUpComplete.tsx
  src/components/auth/SignUpCompleteOption.tsx
  src/components/auth/SignUpForm.tsx
  src/components/auth/SignUpModal.tsx
  src/components/global/button/KakaoButton.tsx
  src/components/global/button/RoundedSquareButton.tsx
  src/components/global/button/button.types.ts
  src/components/global/modal/Modal.tsx
  src/components/global/modal/hooks/useModal.tsx
  src/components/layout/GNB.tsx
Labels: 💄 Design

#24 💄 Design: 모각방 UI 구현
  src/app/globals.css
  src/app/mogak/components/MogakHeader.tsx
  src/app/mogak/components/MyStatus.tsx
  src/app/mogak/components/ScreenBox.tsx
  src/app/mogak/components/Timer.tsx
  src/app/mogak/hooks/useScreenShare.ts
  src/app/mogak/page.tsx
  src/assets/svg/clock.svg
  src/assets/svg/close.svg
  src/assets/svg/link.svg
  src/assets/svg/menu.svg
  src/assets/svg/mogak-banner-bg.svg
  src/assets/svg/pause.svg
  src/assets/svg/person.svg
  src/assets/svg/play.svg
  src/assets/svg/video-fallback.svg
  src/components/global/button/IconButton.tsx
  src/components/global/button/IconTextButton.tsx
  src/components/global/button/button.types.ts
  src/components/global/button/buttonStyle.ts
  src/components/global/chip/MoonChip.tsx
  src/components/global/chip/TextChip.tsx
  src/components/global/chip/chip.style.tsx
  src/components/global/chip/chip.types.ts
  src/components/global/dropdown/DefaultDropdown.tsx
  src/components/global/modal/Modal.tsx
  src/components/global/toggle/TextToggle.tsx
  src/components/global/toggle/toggle.style.tsx
  src/components/global/toggle/toggle.types.ts
  src/utils/convertTime.ts
  tailwind.config.ts
Labels: 🪄 Feat, 💄 Design

#23 💄 Design: 랭킹 페이지 퍼블리싱
  public/fonts/RiaSans-ExtraBold.ttf
  src/app/globals.css
  src/app/layout.tsx
  src/app/rank/page.tsx
  src/assets/svg/banner-block.svg
  src/assets/svg/banner-line.svg
  src/assets/svg/rank-first.svg
  src/assets/svg/rank-second.svg
  src/assets/svg/rank-third.svg
  src/assets/svg/refresh-gray.svg
  src/components/rank/MyLank.tsx
  src/components/rank/RankBanner.tsx
  src/components/rank/TimeDisplay.tsx
  src/components/rank/rankItem.tsx
  src/components/rank/rankList.tsx
Labels: 💄 Design
